name: endy
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.6.5+10

environment:
  sdk: ">=3.0.0 <3.10.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter



  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  provider: ^6.0.2
  cupertino_icons: ^1.0.2
  firebase_core: ^2.4.0
  cloud_firestore: ^4.3.0
  carousel_slider: ^4.1.1
  firebase_auth: ^4.2.3
  intl: any
  smooth_page_indicator: ^1.0.0+2
  # shared_preferences: ^2.0.15
  cached_network_image: ^3.2.1
  path_provider: ^2.0.10
  pinput: ^2.2.10
  flutter_countdown_timer: ^4.1.0
  # qr_code_scanner: ^1.0.0
  permission_handler: ^10.2.0
  # flutter_barcode_scanner: ^2.0.0
  mobile_scanner: ^3.2.0
  xid: ^1.0.7
  image_picker: ^0.8.6
  firebase_storage: ^11.0.9
  photo_view: ^0.14.0
  auto_size_text: ^3.0.0
  google_maps_flutter: ^2.1.8
  geolocator: ^9.0.0
  top_snackbar_flutter: ^3.0.0
  flutter_html: ^3.0.0-alpha.5
  url_launcher: ^6.1.4
  image_cropper: ^4.0.1
  flutter_native_splash: ^2.2.16
  # mask_text_input_formatter: ^2.3.0
  # email_validator: ^2.0.1
  badges: ^3.1.1
  share_plus: ^7.0.2
  anim_search_bar: ^2.0.2
  # algolia: ^1.1.1
  maps_launcher: ^2.0.1
  barcode_widget: ^2.0.2
  firebase_messaging: ^14.2.0
  flutter_local_notifications: ^14.1.1
  timeago: ^3.3.0
  google_fonts: ^4.0.4
  # navigation_history_observer: ^1.1.0
  firebase_performance: ^0.9.0+8
  flutter_bloc: ^8.1.2
  flutter_dotenv: ^5.0.2
  intl_phone_field: ^3.1.0
  typesense: ^0.3.0
  async: ^2.9.0
  connectivity_plus: ^4.0.1
  pluto_menu_bar: ^3.0.1
  web_hover_menu: ^0.0.3
  flutter_portal: ^1.1.3
  web_smooth_scroll: ^1.1.0
  tap_canvas: ^0.9.4
  flutter_localizations:
    sdk: flutter
  visibility_detector: ^0.4.0+2
  google_maps_flutter_web: ^0.5.0
  shared_preferences: ^2.0.18
  go_router: ^9.0.3
  # pdfx: ^2.3.0
  # internet_file: ^1.2.0
  # firebase_performance: ^0.9.0+8

dev_dependencies:
  auto_route_generator: ^7.1.1
  build_runner:
  change_app_package_name: ^1.1.0
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logos/432.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/logos/logoweb.png"
    background_color: "#FFFFFF"
    theme_color: "#f03034"
  # windows:
  #   generate: true
  #   image_path: "path/to/image.png"
  #   icon_size: 48 # min:48, max:256, default: 48
  # macos:
  #   generate: true
  #   image_path: "path/to/image.png"

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
flutter_native_splash:
  color: "#f03034"
  image: assets/logos/logod.png
  android_12:
    color: "#f03034"
    image: assets/logos/logod.png
  android: true
  ios: true
# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - .env
    - assets/sign.png
    # - assets/logo_title.png
    #- assets/endy.az.png
    - assets/logos/logod.png
    - assets/logos/12.png
    - assets/logos/logoweb.png
    # - assets/endy.az_back_white.png
    # - assets/logo_title_blue.png
    - assets/onboard_first.png
    - assets/onboard_second.png
    - assets/onboard_third.png
    # - assets/noimage.jpg
    # - assets/brand.png
    # - assets/android/logo.png
    # - assets/android/logo4.png
    - assets/icons/brand.png
    - assets/icons/category.png
    - assets/icons/filter.png
    - assets/icons/navbar/home.png
    - assets/icons/navbar/card.png
    - assets/icons/navbar/dots.png
    - assets/icons/navbar/list.png
    - assets/icons/navbar/catalog.png
    # - assets/android/background.png
    # - assets/android/background_red.png
    - assets/icons/info.png
    - assets/map.json

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
