// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter_dotenv/flutter_dotenv.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions web = FirebaseOptions(
    apiKey: dotenv.env["apiKeyWeb"] as String,
    appId: dotenv.env["appIdWeb"] as String,
    messagingSenderId: dotenv.env["messagingSenderIdWeb"] as String,
    projectId: dotenv.env["projectIdWeb"] as String,
    authDomain: dotenv.env["authDomainWeb"] as String,
    storageBucket: dotenv.env["storageBucketWeb"] as String,
    measurementId: dotenv.env["measurementIdWeb"] as String,
  );

  static FirebaseOptions android = FirebaseOptions(
    apiKey: dotenv.env["apiKeyAndroid"] as String,
    appId: dotenv.env["appIdAndroid"] as String,
    messagingSenderId: dotenv.env["messagingSenderIdAndroid"] as String,
    projectId: dotenv.env["projectIdAndroid"] as String,
    storageBucket: dotenv.env["storageBucketAndroid"] as String,
  );

  static FirebaseOptions ios = FirebaseOptions(
    apiKey: dotenv.env["apiKeyIos"] as String,
    appId: dotenv.env["appIdIos"] as String,
    messagingSenderId: dotenv.env["messagingSenderIdIos"] as String,
    projectId: dotenv.env["projectIdIos"] as String,
    storageBucket: dotenv.env["storageBucketIos"] as String,
    androidClientId: dotenv.env["androidClientIdIos"] as String,
    iosClientId: dotenv.env["iosClientIdIos"] as String,
    iosBundleId: dotenv.env["iosBundleIdIos"] as String,
  );
}
